### ISSUE TITLE
Error while using the syntax table.columnName for the field argument of the `countIf` measure

### ISSUE THREAD

**Issue by guizer** [squashql/squashql#141]
To Reproduce
- Given you have to table named recommendation with the following columns: (simulation, final_price)
- Execute a query similar to the following one
```typescript
  const query = from("recommendation")
    .select(
      [],
      [],
      [
        countIf(
          "myCountIf",
          "recommendation.simulation",
          criterion("recommendation.final_price", gt(0))
        ),
      ]
    )
    .build();
```

You will get an error in the squashql application similar to 

```
2023-04-05T15:09:58.640+02:00 ERROR 13532 --- [nio-5000-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.clickhouse.client.ClickHouseException: Code: 47. DB::Exception: Missing columns: 'recommendation.simulation' while processing query: 'SELECT count(if(final_price > 0, `recommendation.simulation`, NULL)) AS myCountIf, count() AS _contributors_count_ FROM recommendation LIMIT 10000', required columns: 'final_price' 'recommendation.simulation', maybe you meant: 'final_price'. (UNKNOWN_IDENTIFIER) (version 23.1.3.5 (official build))
, server ClickHouseNode [uri=http://localhost:8123/default]@1228268188] with root cause

java.io.IOException: Code: 47. DB::Exception: Missing columns: 'recommendation.simulation' while processing query: 'SELECT count(if(final_price > 0, `recommendation.simulation`, NULL)) AS myCountIf, count() AS _contributors_count_ FROM recommendation LIMIT 10000', required columns: 'final_price' 'recommendation.simulation', maybe you meant: 'final_price'. (UNKNOWN_IDENTIFIER) (version 23.1.3.5 (official build))

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:194) ~[clickhouse-jdbc-0.3.2-patch11-all.jar:clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:289) ~[clickhouse-jdbc-0.3.2-patch11-all.jar:clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:123) ~[clickhouse-jdbc-0.3.2-patch11-all.jar:clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.AbstractClient.sendAsync(AbstractClient.java:156) ~[clickhouse-jdbc-0.3.2-patch11-all.jar:clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)]
	at com.clickhouse.client.AbstractClient.lambda$execute$0(AbstractClient.java:289) ~[clickhouse-jdbc-0.3.2-patch11-all.jar:clickhouse-jdbc 0.3.2-patch11 (revision: 27f8951)]
```

**Affected version**
1.0.0

**Database**
Clickhouse 22.12

When I execute the following query it works
```typescript
  const query = from("recommendation")
    .select(
      [],
      [],
      [
        countIf(
          "myCountIf",
          "simulation",
          criterion("recommendation.final_price", gt(0))
        ),
      ]
    )
    .build();
```

**Comment by paulbares** [comment]
I think it is fixed by #147. Reopen the issue if it is still there.
