### ISSUE TITLE
Bug when referencing a field declared in a subquery with BigQuery

### ISSUE THREAD

**Issue by guizer** [squashql/squashql#153]
Hello 👋 ,

I am working on a data analysis project with Squashql and BigQuery and I have an issue when referencing a field declared in a subquery.

When executing the following Squashql query
```typescript
  const baseQuery = from("recommendation")
    .innerJoin("current_selling_price")
    .on("recommendation", "product_id", "current_selling_price", "product_id")
    .on("recommendation", "store_id", "current_selling_price", "store_id")
    .innerJoin("sale_aggregation")
    .on("recommendation", "product_id", "sale_aggregation", "product_id")
    .on("recommendation", "store_id", "sale_aggregation", "store_id")
    .select(
      ["recommendation.simulation"],
      [],
      [
        multiply(
          "amount",
          avg("quantity_avg", "sale_aggregation.quantity"),
          avg("current_selling_price_avg", "current_selling_price.price")
        ),
      ]
    )
    .build();
  const query = fromSubQuery(baseQuery)
    .select(["recommendation.simulation"], [], [sum("revenue_sum", "amount")])
    .build();
```

The following query is sent on BigQuery
```sql
select 
	`myproject.mydataset.recommendation`.`simulation`,
	sum(`amount`) as `revenue_sum`,
	count(*) as `_contributors_count_`
from (
	select 
		`myproject.mydataset.recommendation`.`simulation`,
		avg(`myproject.mydataset.sale_aggregation`.`quantity`)*avg(`myproject.mydataset.current_selling_price`.`price`) as `amount`
	from `myproject.mydataset.recommendation`
	inner join `myproject.mydataset.current_selling_price` 
		on `myproject.mydataset.recommendation`.`product_id` = `myproject.mydataset.current_selling_price`.`product_id`
		and `myproject.mydataset.recommendation`.`store_id` = `myproject.mydataset.current_selling_price`.`store_id`
	inner join `myproject.mydataset.sale_aggregation`
		on `myproject.mydataset.recommendation`.`product_id` = `myproject.mydataset.sale_aggregation`.`product_id`
		and `myproject.mydataset.recommendation`.`store_id` = `myproject.mydataset.sale_aggregation`.`store_id`
	group by `myproject.mydataset.recommendation`.`simulation`
) 
group by
	`myproject.mydataset.recommendation`.`simulation`
limit 10000
```

The query fails and I get the following stacktrace
```
2023-05-04T14:28:33.220+02:00  INFO 31764 --- [nio-5000-exec-3] i.squashql.query.database.AQueryEngine   : DatabaseQuery(table=null, subQuery=DatabaseQuery(table=TableDto(name=recommendation, joins=[JoinDto(table=TableDto(name=current_selling_price, joins=[]), type=INNER, mappings=[JoinMappingDto(from=product_id, to=product_id, fromTable=recommendation, toTable=current_selling_price), JoinMappingDto(from=store_id, to=store_id, fromTable=recommendation, toTable=current_selling_price)]), JoinDto(table=TableDto(name=sale_aggregation, joins=[]), type=INNER, mappings=[JoinMappingDto(from=product_id, to=product_id, fromTable=recommendation, toTable=sale_aggregation), JoinMappingDto(from=store_id, to=store_id, fromTable=recommendation, toTable=sale_aggregation)])]), subQuery=null, select=[Field[store=recommendation, name=simulation, type=class java.lang.String]], whereCriteriaDto=null, havingCriteriaDto=null, measures=[BinaryOperationMeasure(alias=amount, expression=null, operator=MULTIPLY, leftOperand=AggregatedMeasure(alias=quantity_avg, expression=null, field=sale_aggregation.quantity, aggregationFunction=avg, criteria=null), rightOperand=AggregatedMeasure(alias=current_selling_price_avg, expression=null, field=current_selling_price.price, aggregationFunction=avg, criteria=null))], rollup=[], limit=-1), select=[Field[store=recommendation, name=simulation, type=class java.lang.String]], whereCriteriaDto=null, havingCriteriaDto=null, measures=[AggregatedMeasure(alias=revenue_sum, expression=null, field=amount, aggregationFunction=sum, criteria=null), AggregatedMeasure(alias=_contributors_count_, expression=null, field=*, aggregationFunction=count, criteria=null)], rollup=[], limit=10000) translated into sql='select `myproject.mydataset.recommendation`.`simulation`, sum(`amount`) as `revenue_sum`, count(*) as `_contributors_count_` from (select `myproject.mydataset.recommendation`.`simulation`, avg(`myproject.mydataset.sale_aggregation`.`quantity`)*avg(`myproject.mydataset.current_selling_price`.`price`) as `amount` from `myproject.mydataset.recommendation` inner join `myproject.mydataset.current_selling_price` on `myproject.mydataset.recommendation`.`product_id` = `myproject.mydataset.current_selling_price`.`product_id` and `myproject.mydataset.recommendation`.`store_id` = `myproject.mydataset.current_selling_price`.`store_id` inner join `myproject.mydataset.sale_aggregation` on `myproject.mydataset.recommendation`.`product_id` = `myproject.mydataset.sale_aggregation`.`product_id` and `myproject.mydataset.recommendation`.`store_id` = `myproject.mydataset.sale_aggregation`.`store_id` group by `myproject.mydataset.recommendation`.`simulation`) group by `myproject.mydataset.recommendation`.`simulation` limit 10000'
2023-05-04T14:28:35.727+02:00 ERROR 31764 --- [nio-5000-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: com.google.cloud.bigquery.BigQueryException: Unrecognized name: `myproject.mydataset.recommendation` at [1:8]] with root cause

com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://www.googleapis.com/bigquery/v2/projects/myproject/queries
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "location" : "q",
    "locationType" : "parameter",
    "message" : "Unrecognized name: `myproject.mydataset.recommendation` at [1:8]",
    "reason" : "invalidQuery"
  } ],
  "message" : "Unrecognized name: `myproject.mydataset.recommendation` at [1:8]",
  "status" : "INVALID_ARGUMENT"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146) ~[google-api-client-2.0.1.jar:2.0.1]
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118) ~[google-api-client-2.0.1.jar:2.0.1]
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37) ~[google-api-client-2.0.1.jar:2.0.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:439) ~[google-api-client-2.0.1.jar:2.0.1]
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111) ~[google-http-client-1.42.3.jar:1.42.3]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:525) ~[google-api-client-2.0.1.jar:2.0.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:466) ~[google-api-client-2.0.1.jar:2.0.1]
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:576) ~[google-api-client-2.0.1.jar:2.0.1]
	at com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.queryRpc(HttpBigQueryRpc.java:718) ~[google-cloud-bigquery-2.19.1.jar:2.19.1]
	at com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1322) ~[google-cloud-bigquery-2.19.1.jar:2.19.1]
	at com.google.cloud.bigquery.BigQueryImpl$35.call(BigQueryImpl.java:1319) ~[google-cloud-bigquery-2.19.1.jar:2.19.1]
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:103) ~[gax-2.19.5.jar:2.19.5]
	at com.google.cloud.bigquery.BigQueryRetryHelper.run(BigQueryRetryHelper.java:86) ~[google-cloud-bigquery-2.19.1.jar:2.19.1]
	at com.google.cloud.bigquery.BigQueryRetryHelper.runWithRetries(BigQueryRetryHelper.java:49) ~[google-cloud-bigquery-2.19.1.jar:2.19.1]
	at com.google.cloud.bigquery.BigQueryImpl.queryRpc(BigQueryImpl.java:1318) ~[google-cloud-bigquery-2.19.1.jar:2.19.1]
	at com.google.cloud.bigquery.BigQueryImpl.query(BigQueryImpl.java:1306) ~[google-cloud-bigquery-2.19.1.jar:2.19.1]
	at io.squashql.query.database.BigQueryEngine.retrieveAggregates(BigQueryEngine.java:159) ~[squashql-bigquery-1.0.2.jar:na]
	at io.squashql.query.database.AQueryEngine.execute(AQueryEngine.java:96) ~[squashql-core-1.0.2.jar:na]
	at io.squashql.query.QueryExecutor.execute(QueryExecutor.java:119) ~[squashql-core-1.0.2.jar:na]
	at io.squashql.spring.web.rest.QueryController.execute(QueryController.java:45) ~[squashql-server-1.0.2.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:731) ~[tomcat-embed-core-10.1.5.jar:6.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.4.jar:6.0.4]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[tomcat-embed-core-10.1.5.jar:6.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.access.intercept.AuthorizationFilter.doFilter(AuthorizationFilter.java:100) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:145) ~[spring-security-oauth2-resource-server-6.0.1.jar:6.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:351) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267) ~[spring-web-6.0.4.jar:6.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar:6.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar:6.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.4.jar:6.0.4]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar:6.0.4]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.5.jar:10.1.5]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

From what I understand BigQuery does not understand that it has to look at the  `myproject.mydataset.recommendation`.`simulation ` column from the subquery.

The following query works on BigQuery because I use an alias for the subquery
```sql
select 
	`mysubquery`.`simulation`,
	sum(`amount`) as `revenue_sum`,
	count(*) as `_contributors_count_`
from (
	select 
		`myproject.mydataset.recommendation`.`simulation`,
		avg(`myproject.mydataset.sale_aggregation`.`quantity`)*avg(`myproject.mydataset.current_selling_price`.`price`) as `amount`
	from `myproject.mydataset.recommendation`
	inner join `myproject.mydataset.current_selling_price` 
		on `myproject.mydataset.recommendation`.`product_id` = `myproject.mydataset.current_selling_price`.`product_id`
		and `myproject.mydataset.recommendation`.`store_id` = `myproject.mydataset.current_selling_price`.`store_id`
	inner join `myproject.mydataset.sale_aggregation`
		on `myproject.mydataset.recommendation`.`product_id` = `myproject.mydataset.sale_aggregation`.`product_id`
		and `myproject.mydataset.recommendation`.`store_id` = `myproject.mydataset.sale_aggregation`.`store_id`
	group by 
            `myproject.mydataset.recommendation`.`simulation`
) mysubquery
group by
	`myproject.mydataset.recommendation`.`simulation`
limit 10000
```

**Comment by guizer** [comment]
As explained by @paulbares my query is wrong.

Here is the query that I should write to reference the simulation from the subquery correctly

```typescript
  const query = fromSubQuery(baseQuery)
    .select(["simulation"], [], [sum("revenue_sum", "amount")])
    .build();
```
