### ISSUE TITLE
Support Datetime function in select: year, semester, quarter and month

### ISSUE THREAD

**Issue by paulbares** [squashql/squashql#181]
If a column is of type DATE, we should be able to use the following date functions: semester, quarter, year and month. 

Example:
```java
var query = Query.from(this.storeName)
          .select(List.of("YEAR(date_sales)"), List.of(CountMeasure.INSTANCE))
          .build();
this.executor.execute(query);
```
Currently, it throws:
```
io.squashql.query.exception.FieldNotFoundException: Cannot find field with name Year(date_sales)

	at io.squashql.query.database.AQueryEngine.lambda$createFieldSupplier$1(AQueryEngine.java:70)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.squashql.query.QueryExecutor.createQueryScope(QueryExecutor.java:268)
	at io.squashql.query.QueryExecutor.execute(QueryExecutor.java:150)
	at io.squashql.query.QueryExecutor.execute(QueryExecutor.java:129)
```
Because select only supports column table names. 

To reproduce, use this test in `ATestPeriodComparison`

```java
  @Test
  void test() {
    var query = Query.from(this.storeName)
            .select(List.of("YEAR(date_sales)"), List.of(CountMeasure.INSTANCE))
            .build();
    Table finalTable = this.executor.execute(query);
    finalTable.show();
  }
```

Maybe we should not let the user write the string himself but provide a function to do this. That function would generate a string with special characters that could be identified by SquashQL to understand the user wants to use an SQL function and we could adapt it to the underlying database if needed. For instance:

```java
  static String year(String column) {
    return "__YEAR__(column)";
  }

...

select(List.of(year("date_sales")), List.of(CountMeasure.INSTANCE))
```
By doing so, the type of the column can be known (integer in case of year, semester, quarter, month).

We are already using something similar to identify grouping functions. See SqlUtils and `  static final Pattern GROUPING_PATTERN = Pattern.compile("___grouping___(.*)___");
`

**Comment by paulbares** [comment]
Fixed by #182
