### ISSUE TITLE
Compare with parent error when having null parent value

### ISSUE THREAD

**Issue by robin-lcr** [squashql/squashql#233]
When running a comparison with parent query (divide type), I got the following error because one of my ancestors has a null value.

```
2024-01-10T18:22:53.338+01:00 ERROR 11660 --- [nio-5000-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "row[index]" is null] with root cause

java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "row[index]" is null
	at io.squashql.query.ParentComparisonExecutor$ShiftProcedure.test(ParentComparisonExecutor.java:43) ~[squashql-core-1.4.2.jar:na]
	at io.squashql.query.ParentComparisonExecutor$ShiftProcedure.test(ParentComparisonExecutor.java:26) ~[squashql-core-1.4.2.jar:na]
	at io.squashql.query.AComparisonExecutor.lambda$compare$1(AComparisonExecutor.java:60) ~[squashql-core-1.4.2.jar:na]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at io.squashql.query.AComparisonExecutor.compare(AComparisonExecutor.java:50) ~[squashql-core-1.4.2.jar:na]
	at io.squashql.query.Evaluator.executeComparator(Evaluator.java:97) ~[squashql-core-1.4.2.jar:na]
	at io.squashql.query.Evaluator.visit(Evaluator.java:92) ~[squashql-core-1.4.2.jar:na]
	at io.squashql.query.Evaluator.visit(Evaluator.java:19) ~[squashql-core-1.4.2.jar:na]
	at io.squashql.query.ComparisonMeasureReferencePosition.accept(ComparisonMeasureReferencePosition.java:86) ~[squashql-core-1.4.2.jar:na]
	...
```

Here is part of `readFromTable` variable in `AComparisonExecutor` class when the bug occurs on brand ancestor. 
```
+-------------+----------------------+----------------------+---------------------+
|       brand | turnover_initial_sum | _contributors_count_ |  margin_initial_sum |
+-------------+----------------------+----------------------+---------------------+
|     PAMPERS |    688177.1476999999 |                 2817 |  248593.03204666666 |
|         ... |                  ... |                  ... |                 ... |
|        null |   3737566.3978999993 |                  339 |  1557586.8186738396 |
|      NESTLE |    874721.3929000002 |                 1608 |  346017.77090668294 |
|         ... |                  ... |                  ... |                 ... |
| ___total___ | 1.0601323782199985E8 |               159749 | 4.304484896750492E7 |
+-------------+----------------------+----------------------+---------------------+
```

Is it possible to prevent this error and to still return valid ratio values for all null ancestors values?

**Comment by paulbares** [comment]
@robin-lcr Thank you for reporting this issue. It will be addressed soon.
